<?php

/**
 * @file
 * Hook implementations for REST UI module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function restui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'restui.edit':
      return '<p>' . t('Here you can restrict which HTTP methods should this resource support. And within each method, the available serialization formats and authentication providers.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function restui_theme() {
  return array(
    // List resources.
    'restui_resource_info' => array(
      'variables' => array(
        'granularity' => array(),
        'configuration' => array(),
        ),
      'template' => 'restui-resource-info',
    ),
  );
}
